import Link from 'next/link';

export const metadata = {
  title: 'Terms of Use | Bureaucracy Decoder',
  description: 'Terms of Use for Bureaucracy Decoder - Los Angeles Zoning Copilot',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-stone-50">
      {/* Header */}
      <header className="bg-white border-b border-stone-200 py-4">
        <div className="container mx-auto px-6">
          <Link href="/" className="text-xl font-bold text-stone-800 hover:text-amber-600">
            Bureaucracy Decoder
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="container mx-auto px-6 py-12 max-w-3xl">
        <h1 className="text-4xl font-serif font-bold text-stone-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-stone-500 mb-8">Last updated: December 6, 2025</p>

        <div className="prose prose-stone max-w-none space-y-8">
          {/* Introduction */}
          <section>
            <p className="text-stone-700 leading-relaxed">
              These Terms of Use (&quot;Terms&quot;) govern your access to and use of the Bureaucracy Decoder
              service (the &quot;Service&quot;) provided by Leafspire LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
              By accessing or using the Service, you agree to be bound by these Terms. If you do not agree
              to these Terms, do not use the Service.
            </p>
          </section>

          {/* No Legal or Professional Advice */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              No Legal or Professional Advice
            </h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              The Service and all content provided through it are for <strong>informational purposes only</strong>.
              The Service does not constitute legal, land-use, architectural, engineering, tax, or other
              professional advice, and you should not rely on it as a substitute for advice from a qualified
              professional licensed in the relevant jurisdiction.
            </p>
            <p className="text-stone-700 leading-relaxed mb-4">
              Your use of the Service does <strong>not</strong> create an attorney–client relationship, nor any
              other professional relationship, between you and Leafspire LLC or any of its owners, members,
              managers, employees, contractors, or affiliates.
            </p>
            <p className="text-stone-700 leading-relaxed font-medium bg-amber-50 p-4 border-l-4 border-amber-500">
              We do not guarantee that use of the Service will result in any particular outcome, including
              without limitation the issuance of permits, approvals, entitlements, financing, or successful
              completion of any project.
            </p>
          </section>

          {/* No Warranties */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              No Warranties; No Guarantee of Accuracy
            </h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              Zoning, land-use, and related regulations change frequently and may be subject to interpretation,
              exceptions, and site-specific conditions. The Service relies on third-party data sources and AI
              models that may be incomplete, outdated, or inaccurate.
            </p>
            <p className="text-stone-700 leading-relaxed mb-4 uppercase font-medium bg-stone-100 p-4 border-l-4 border-amber-500">
              THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS, WITHOUT WARRANTIES OF ANY KIND,
              WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF ACCURACY,
              COMPLETENESS, RELIABILITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>
            <p className="text-stone-700 leading-relaxed">
              You acknowledge that any output generated by the Service may be incorrect or misleading and that
              you will independently verify any results against official sources before relying on them.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              Limitation of Liability
            </h2>
            <p className="text-stone-700 leading-relaxed mb-4 uppercase font-medium bg-stone-100 p-4 border-l-4 border-amber-500">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL LEAFSPIRE LLC, ITS OWNERS,
              MEMBERS, MANAGERS, EMPLOYEES, CONTRACTORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA,
              GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF (OR
              INABILITY TO USE) THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE),
              OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="text-stone-700 leading-relaxed uppercase font-medium bg-stone-100 p-4 border-l-4 border-amber-500">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL AGGREGATE LIABILITY FOR ANY AND ALL CLAIMS
              ARISING OUT OF OR RELATING TO THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE AMOUNT YOU
              PAID TO USE THE SERVICE IN THE TWELVE (12) MONTHS PRIOR TO THE EVENT GIVING RISE TO THE CLAIM;
              OR (B) $100.
            </p>
          </section>

          {/* User Responsibility */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              User Responsibility
            </h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              You are solely responsible for:
            </p>
            <ol className="list-decimal list-inside text-stone-700 space-y-2 ml-4">
              <li>
                Verifying any information provided by the Service against current, official sources (including
                the City of Los Angeles Municipal Code, specific plans, ordinances, and official zoning maps); and
              </li>
              <li>
                Ensuring that your projects and decisions comply with all applicable laws, regulations, and
                professional standards.
              </li>
            </ol>
            <p className="text-stone-700 leading-relaxed mt-4 font-medium">
              You agree that you will not use the Service as the sole basis for making legal, financial,
              permitting, design, or construction decisions.
            </p>
          </section>

          {/* Indemnification */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              Indemnification
            </h2>
            <p className="text-stone-700 leading-relaxed">
              You agree to indemnify, defend, and hold harmless Leafspire LLC and its owners, members, managers,
              employees, contractors, and affiliates from and against any and all claims, liabilities, damages,
              losses, and expenses (including reasonable attorneys&apos; fees) arising out of or related to:
              (a) your use of the Service; (b) your violation of these Terms; or (c) your violation of any
              rights of a third party or any applicable law or regulation.
            </p>
          </section>

          {/* Data Sources */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              Data Sources and Currency
            </h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              The Service is based on publicly available data from the City of Los Angeles Municipal Code
              and related sources. This data:
            </p>
            <ul className="list-disc list-inside text-stone-700 space-y-2 ml-4">
              <li>May be delayed and may not reflect the most current ordinances or regulations;</li>
              <li>Does not include all specific plans, overlay zones, discretionary actions, or site-specific conditions;</li>
              <li>May not reflect pending legislation or recently adopted amendments; and</li>
              <li>Is processed by AI systems that may introduce errors or omissions.</li>
            </ul>
            <p className="text-stone-700 leading-relaxed mt-4">
              You must always verify information with official City of Los Angeles resources, including{' '}
              <a
                href="https://planning.lacity.org"
                target="_blank"
                rel="noopener noreferrer"
                className="text-amber-600 hover:underline"
              >
                planning.lacity.org
              </a>{' '}
              and{' '}
              <a
                href="https://codelibrary.amlegal.com/codes/los_angeles"
                target="_blank"
                rel="noopener noreferrer"
                className="text-amber-600 hover:underline"
              >
                the official Municipal Code
              </a>
              , and with any other applicable authorities.
            </p>
          </section>

          {/* Changes to Terms */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              Changes to These Terms
            </h2>
            <p className="text-stone-700 leading-relaxed">
              We may update these Terms from time to time. If we make material changes, we will notify you
              by posting the updated Terms on this page with a new &quot;Last updated&quot; date. Your continued use
              of the Service after any changes indicates your acceptance of the updated Terms.
            </p>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              Governing Law
            </h2>
            <p className="text-stone-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the Commonwealth of
              Pennsylvania, without regard to its conflict of law provisions.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-2xl font-serif font-bold text-stone-900 mb-4">
              Contact Us
            </h2>
            <p className="text-stone-700 leading-relaxed">
              If you have questions about these Terms, please contact us at{' '}
              <a href="mailto:leafspire@gmail.com" className="text-amber-600 hover:underline">
                leafspire@gmail.com
              </a>.
            </p>
          </section>
        </div>

        {/* Back link */}
        <div className="mt-12 pt-8 border-t border-stone-200">
          <Link href="/" className="text-amber-600 hover:underline text-sm">
            &larr; Back to Bureaucracy Decoder
          </Link>
        </div>
      </main>
    </div>
  );
}
